[tasks.watch]
command="cargo"
args=["watch", "-x", "test"]

[tasks.build]
command="cargo"
args=["build"]

[tasks.test]
command="cargo"
args=["test"]

[tasks.doc]
command="cargo"
args=["watch", "-x", "doc"]

[tasks.publish]
command="cargo"
args=["publish"]
dependencies=["doc", "test"]